services:
    app:
        build: ./
        ports:
            - 8060:5173
        volumes:
            - /home/jamie/Games/ROMs:/games
        env_file:
            - .env.docker
    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
    meilisearch:
        image: getmeili/meilisearch:v1.0
        restart: unless-stopped
